language: go

go:
  - "1.10.x"

before_install:
  - go get -t github.com/Masterminds/glide
  - go get -t github.com/codeclimate/test-reporter
  - cmake .
  - make
  
before_script:
  - test-reporter before-build

script:
  - make cover-check

after_script:
  - test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
