datadir = "/aergo/data"
enableprofile = false
profileport = 6060
usetestnet = true

[rpc]
netserviceaddr = "0.0.0.0"
netserviceport = 7845
nstls = false
nscert = ""
nskey = ""
nsallowcors = false

[p2p]
netprotocoladdr = ""
netprotocolport = 7846
npbindaddr = "0.0.0.0"
npbindport = 7846
nptls = false
npcert = ""
npkey = ""
npmaxpeers = "100"
nppeerpool = "100"
npaddpeers = [
]
npexposeself = false
npusepolaris = true

[blockchain]
blockchainplaceholder = false

[mempool]
showmetrics = false
dumpfilepath = "/aergo/mempool.dump"
enablefadeout = true
fadeoutperiod = 12

[consensus]
enablebp = false
